config/routes.rb
Facebook::Application.routes.draw do
  resources :businesses
  resources :coupons
  root :to => 'static_pages#home'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/') 
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get 'about', :controller => 'static_pages', :action => 'about', as: 'about'
  get 'contact', :controller => 'static_pages', :action => 'contact', as: 'contact'
  get 'oops', :controller => 'static_pages', :action => 'oops', as: 'oops'

end

app/models/business.rb
class Business < ActiveRecord::Base
  attr_accessible :name, :place

  has_many :coupons
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  attr_accessible :business_id, :code, :desc, :discount, :token, :url, :message
  belongs_to :business



end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap  do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.name = auth.info.name
  		user.oauth_token = auth.credentials.token
  		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  		user.save!
  	end
  end

  def facebook
  	@facebook ||= Koala::Facebook::API.new(oauth_token)
 	  block_given? ? yield(@facebook) : @facebook
		rescue Koala::Facebook::APIError => e
  		logger.info e.to_s
  		nil # or consider a custom null object
	end


  def post_wall(message="Having a great time with my buddies!")
  	facebook { |fb| fb.put_wall_post message }
  end

  #Default check-in to University of Champagne, IL
  def check_in (idstring='163536409904')
  facebook { |fb| fb.put_wall_post("Having a great time!", :place => idstring)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

   def signed_in?
    !current_user.nil?
  end

before_filter :remove_www!

protected

def remove_www!
  if Rails.env.production? and request.host[0..3] == "www."
    redirect_to "#{request.protocol}#{request.host_with_port[4..-1]}#{request.fullpath}", :status => 301
  end
end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businesses }
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @business = Business.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/new
  # GET /businesses/new.json
  def new
    @business = Business.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @business }
    end
  end

  # GET /businesses/1/edit
  def edit
    @business = Business.find(params[:id])
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(params[:business])

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  # GET /coupons
  # GET /coupons.json

  before_filter :log_in, :only => [:show]

  def index
    @coupons = Coupon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coupons }
    end
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
    coupon_id = params[:id]  
    if current_user && coupon_id
      puts "condition worked"
      @coupon = Coupon.find_by_id(coupon_id)
      current_user.post_wall 
      current_user.check_in 
      session[:coupon_id] = nil
      puts "went through all the method"
    else 
    redirect_to oops_path # We need to change this is to sorry 404 page

      redirect_to root_path # We need to change this is to sorry 404 page

    end
    

  end

  # GET /coupons/new
  # GET /coupons/new.json
  def new
    @coupon = Coupon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coupon }
    end
  end

  # GET /coupons/1/edit
  def edit
    @coupon = Coupon.find_by_id(params[:id])
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(params[:coupon])

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to @coupon, notice: 'Coupon was successfully created.' }
        format.json { render json: @coupon, status: :created, location: @coupon }
      else
        format.html { render action: "new" }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /coupons/1
  # PUT /coupons/1.json
  def update
    @coupon = Coupon.find_by_id(params[:id])

    respond_to do |format|
      if @coupon.update_attributes(params[:coupon])
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon = Coupon.find_by_id(params[:id])
    @coupon.destroy

    respond_to do |format|
      format.html { redirect_to coupons_url }
      format.json { head :no_content }
    end
  end

  private

  def log_in
    if !current_user 
      session[:coupon_id] = params[:id]
      redirect_to '/auth/facebook'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env["omniauth.auth"])
		
		session[:user_id] = user.id 
		if session[:coupon_id]
			redirect_to coupon_path(session[:coupon_id])
		else
			redirect_to root_path
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_user && session[:coupon_id]
    	redirect_to coupon_url(session[:coupon_id])
    end
  end
  def oops
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary'  %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<div class="top">
	<h1>Editing business</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @business %> |
	<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/index.html.erb
<div class="top">    
    <h1>Listing businesses</h1>
    <br>
    <table class="table table-bordered table-hover">
      <tr>
        <th>Name</th>
        <th>Place</th>
      </tr>

    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.place %></td>
        <td><%= link_to 'Show', business, :class => 'btn btn-primary'  %></td>
        <td><%= link_to 'Edit', edit_business_path(business), :class => 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', business, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New Business', new_business_path %>
</div>

app/views/businesses/new.html.erb
<div class="top">
	<h1>New business</h1>

	<%= render 'form' %>

	<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/show.html.erb
<div class="top">
	<p id="notice"><%= notice %></p>
	
	<p>
	  <b>Name:</b>
	  <%= @business.name %>
	</p>
	
	<p>
	  <b>Place:</b>
	  <%= @business.place %>
	</p>


	<%= link_to 'Edit', edit_business_path(@business) %> |
	<%= link_to 'Back', businesses_path %>
</div>

app/views/coupons/_form.html.erb
<%= form_for(@coupon) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row span12">
  <div class="span12">
    <%= f.label 'Message' %><br />
    <%= f.text_field :message %>
  </div>
</div>
<div class="row span12">
  <div class="span12">
    <%= f.label 'Description' %><br />
    <span style="height: 1em;">
    <%= f.text_area :desc %>
    </span>
  </div>
</div>
  <div class="row span12">
    <div class="span12">
      <%= f.label 'Discount Code' %><br />
      <%= f.text_field :code %>
    </div>
  </div>
  <div class="row span12">
    <div class="span12">
      <%= f.label 'Percentage Off' %><br />
      <%= f.number_field :discount %>
    </div>
  </div>
  
  <div class="row span12">
    <div class="span12">
      <%= f.label 'Business ID' %><br />
      <%= f.number_field :business_id %>
    </div>
  </div>

  <div class="row span12">
    <div class="span12">
      <%= f.label 'Upload Coupon Image' %><br />
      <%= f.text_field :url %>
    </div>
  </div>


  <div class="row span12">
    <div class="actions span12">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  </div>


  
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<div class="top">
    <h1>All Discount Codes</h1>
    <br>
    <table class="table table-bordered table-hover">
      <tr>
        <th>Business Name</th>
        <th>Description</th>
        <th>Discount Code</th>
        <th>Percentage Off</th>
      </tr>

    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.business.name %></i></td>
        <td><%= coupon.desc %></td>
        <td><%= coupon.code %></td>
        <td><%= coupon.discount %></td>
        <td><%= link_to 'View', coupon, :class => 'btn btn-primary' %></td>

        <td><%= link_to 'Edit', edit_coupon_path(coupon), :class => 'btn btn-info' %></td>
        <td><%= link_to 'Remove', coupon, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>

    <br />
</div>
<%= link_to 'New Coupon', new_coupon_path %>

app/views/coupons/new.html.erb
<div class="top">
	<h1>New coupon</h1>

	<%= render 'form' %>

	<%= link_to 'Back', coupons_path %>
</div>

app/views/coupons/show.html.erb
<div class="top">

	<p id="notice"><%= notice %></p>

	<!-- Display only if there is an account -->

	<% if @coupon.discount > 0 %>

	<div class="row show">
		<div class="span12 show">
			<h2><b>Thanks for stopping by <%= @coupon.business.name %>!</b></h2>
			<br>
			<%= image_tag(@coupon.url, :class => 'rounded' ) %>
			<br>
			<br>
			<h3><%= @coupon.code %></h3>
			<p>Thanks for checking in at <%= @coupon.business.name  %>!</p>  
			<p>Show this coupon to the cashier to receive <%= @coupon.desc %>, good for <%= @coupon.discount %>% off your order!</p>
		</div>	
	</div>

	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Average+Sans|Buenard:400,700|Leckerli+One|Pacifico' rel='stylesheet' type='text/css'>

  <script type="text/javascript">if (window.location.hash == '#_=_')window.location.hash = '';</script>

</head>
<body>


<div class="container">
	
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
	 
	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			<span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	 
	      <!-- Be sure to leave the brand out there if you want it shown -->
	      <%= link_to 'Tapp.io', root_url, :class => 'brand' %>
	 
	      <!-- Everything you want hidden at 940px or less, place within here -->
	      <div class="nav-collapse collapse">
	        <!-- .nav, .navbar-search, .navbar-form, etc -->
	        <ul class="nav">
	        	<li><%= link_to 'Coupons', coupons_url %></li>
	        	<li><%= link_to 'Businesses', businesses_url %></li>	
	        	<li><%= link_to 'About', about_url %></li>
	        	<li><%= link_to 'Contact', contact_url %></li>
	        </ul>
	      </div>
	 
	    </div>
	  </div>
	</div>





<%= yield %>

</div>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="top">

	<h4> This NFC app has been created by:</h4>

	<ul>
	<li>Joe Villanueva</li>
	<li>Mike Chau</li>
	 <li>Jean-Nicholas Hould</li>
	<li>Vaibhav Puri</li>
	</ul>
	<br/>
	<h4> What does this app do?:</h4>

	<p>We esesntially connect NFC and the Facebook Actions. A business creates and defines a coupon on our web app which is rendered when a user taps a NFC smart poster.</p>
	<p>
	In return for each coupon rendered, the business gets the user to "Post" on his or her wall about their business and "check-in" at the business location. 
	</p>

	<br/>

	<h4>Thanks for testing our App!</h4>

</div>

app/views/static_pages/contact.html.erb
<body class="container">

  <div class="row" style="margin-top: 40px;">
    <div class="span12" style="font-family">
      <h1><span style="font-family: 'Pacifico', 'Leckerli One';">Tapp.io</span></h1>
    </div>
  </div>

  <br>
  <br>
  <br>

  <div class="row">
    <div class="span6">
      <div class="span2">
        <img src="https://twimg0-a.akamaihd.net/profile_images/2476685982/eightbit-b9f05c06-8ffb-43a5-9e84-fca17740c25f_reasonably_small.png" class="img-circle" height="128" width="128">
      </div>
      <div class="span3 well">
        <p><b>Joe Villanueva</b></p>
        <p>HTML5 CSS3 jQuery UX Rails</p>
        <p>Send Joe a shoutout on Twitter at <a href="http://www.twitter.com/joevillanueva22" target="blank">@joevillanueva22</a>, or check his Github account out <a href="https://github.com/joevillanueva" target="blank">here.</a></p>
      </div>    
    </div>
    <div class="span6">
      <div class="span2">
        <img src="https://twimg0-a.akamaihd.net/profile_images/1255273126/skyav_reasonably_small.png" class="img-circle" height="128" width="128">
      </div>
      <div class="span3 well">
        <p><b>Mike Chau</b></p>
        <p>Javascript Rails</p>
        <p>Send Mike a shoutout on Twitter at <a href="http://www.twitter.com/money_mikec" target="blank">@money_mikec</a>, or check his Github account out <a href="https://github.com/mikechau" target="blank">here.</a></p>
      </div>    
    </div>
  </div>
  <br>
  <br>  
  <div class="row">
    <div class="span6">
      <div class="span2">
        <img src="https://si0.twimg.com/profile_images/1541318371/Vaibhav_Puri_reasonably_small.jpg" class="img-circle" height="128" width="128">
      </div>
      <div class="span3 well">
        <p><b>Vaibhav Puri</b></p>
        <p>Rails<p>
        <p>Send Vaibhav a shoutout on Twitter at <a href="http://www.twitter.com/vaibpuri" target="blank">@vaibpuri</a>, or check his Github account out <a href="https://github.com/vaibhavpuri2208" target="blank">here.</a></p>
      </div>    
    </div>
    <div class="span6">
      <div class="span2">
        <img src="https://twimg0-a.akamaihd.net/profile_images/2718589957/fc0ff8457f90ad69caca7365a67e381b.jpeg" class="img-circle" height="128" width="128">
      </div>
      <div class="span3 well">
        <p><b>Nick Hould</b></p>
        <p>Rails</p>
        <p>Send Nick a shoutout on Twitter at <a href="http://www.twitter.com/nicholashould" target="blank">@nicholashould</a>, or check his Github account out <a href="https://github.com/nickhould" target="blank">here.</a></p>
      </div>    
    </div>
  </div>  
</body>

app/views/static_pages/home.html.erb
<div class="center hero-unit top">
  <h1>Welcome to <span style="font-family: 'Pacifico', 'Leckerli One';">Tapp.io</span></h1>
  <img src="nfc.png">
  <br>
  <br>
  <p>Create an account, order NFC chips, and start engaging your customers!</p>
  <br>
</div>
<div class="row">
	<div class="span12">
	  <% if current_user %>
	   <div>Signed in as <strong><%= current_user.name %></strong>!</br>
	    <%= link_to "Sign out", signout_path %></div>
	  <% else %>
	    <%= link_to "Sign in with Facebook", "/auth/facebook"%></br>
	  <% end %>

	  <%= link_to "Sign up as a business", new_business_path %>
	</div>

app/views/static_pages/oops.html.erb
<div class="top">
	<span style="text-align: center; display: block; margin: auto;">
		<h1>Oh hayyyyyyyyyyy!</h1>
		<br>
		<%= image_tag("http://www.studentsoftheworld.info/sites/animals/img/28051_puppy4.jpg" ) %>
		<br>
		<br>
		<h3>That coupon expired! I'm sowwy!</h3>
	</span>
</div>